# Generated by Django 3.2.6 on 2021-08-30 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0002_auto_20210830_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plateNum',
            field=models.CharField(help_text='Enter license plate number (e.g. PPP1234)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,3}[0-9]{1,4}$', 'License Plate Number should follow the format (PPP1234) no spaces required')], verbose_name='License Plate Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(help_text="Enter visitor's name (e.g. Tan Ah Lee)", max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Name must only contain characters')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitUnit',
            field=models.CharField(help_text='Enter visited unit (e.g. 2-14-2)', max_length=10, validators=[django.core.validators.RegexValidator('^\\d-\\d{1,2}-\\d$', 'Unit number must match X-XX-X where X is number')], verbose_name='Visited Unit'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorPlateNum',
            field=models.CharField(help_text="Enter visitor vehicle's license plate number (e.g. PPP1234)", max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,3}[0-9]{1,4}$', 'License Plate Number should follow the format (PPP1234) no spaces required')], verbose_name='Visitor License Plate Number'),
        ),
    ]
