# Generated by Django 3.2.6 on 2021-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0003_auto_20210830_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
