# Generated by Django 3.2.6 on 2021-10-13 08:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=0, size=[200, 200], upload_to='images'),
        ),
    ]
