# Generated by Django 3.2.6 on 2021-10-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
