# Generated by Django 3.2.6 on 2021-11-02 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0009_auto_20211102_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEnterDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LPR.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerEnterDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LPR.vehicle')),
            ],
        ),
    ]
