# Generated by Django 3.2.6 on 2021-11-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0010_ownerenterdatetime_visitorenterdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerenterdatetime',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
