# Generated by Django 3.2.6 on 2021-11-12 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0011_alter_ownerenterdatetime_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorenterdatetime',
            name='exitDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
