# Generated by Django 3.2.6 on 2021-11-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0012_visitorenterdatetime_exitdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorenterdatetime',
            name='exitDateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
