# Generated by Django 3.2.6 on 2021-11-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0013_alter_visitorenterdatetime_exitdatetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['unit']},
        ),
    ]
