# Generated by Django 3.2.6 on 2021-11-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0014_alter_owner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['visitUnit']},
        ),
    ]
