# Generated by Django 3.2.6 on 2022-11-13 10:47

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0016_alter_visitorenterdatetime_exitdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='A',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=-1, scale=None, size=[200, 200], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(help_text="Enter Resident's name (e.g. Tan Soon Lee)", max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Name must only contain characters')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='unit',
            field=models.CharField(help_text="Enter Resident's unit number (e.g. 2-12-1)", max_length=10, validators=[django.core.validators.RegexValidator('^\\d-\\d{1,2}-\\d$', 'Unit number must match X-XX-X where X is number')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plateNum',
            field=models.CharField(help_text='Enter license plate number (e.g. PPP1234)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,3}[0-9]{1,4}[A-Za-z]{0,2}$', 'License Plate Number should follow the format (PPP1234) no spaces required')], verbose_name='License Plate Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorPlateNum',
            field=models.CharField(help_text="Enter visitor vehicle's license plate number (e.g. PPP1234)", max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,3}[0-9]{1,4}[A-Za-z]{0,2}$', 'License Plate Number should follow the format (PPP1234) no spaces required')], verbose_name='Visitor License Plate Number'),
        ),
    ]
