# Generated by Django 3.2.6 on 2022-11-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0017_auto_20221113_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='A',
            new_name='Balance',
        ),
    ]
