# Generated by Django 3.2.6 on 2022-11-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0019_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='', help_text='Enter Your Email', max_length=254, verbose_name='Email'),
        ),
    ]
