# Generated by Django 3.2.6 on 2022-11-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPR', '0020_alter_visitor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='Balance',
        ),
        migrations.AddField(
            model_name='visitorenterdatetime',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
